# Generated by Django 3.2.20 on 2023-12-26 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='slug',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
