# Generated by Django 3.2.20 on 2024-01-04 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0002_vehicle_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('vehicle_no', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('operator_class', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('amount', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
