# Generated by Django 3.2.20 on 2024-01-07 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0005_receipt_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='vehicle_number',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='price',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
