# Generated by Django 3.2.20 on 2024-01-14 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0006_auto_20240107_2353'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='shift_name',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
