# Generated by Django 3.2.20 on 2024-01-14 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0007_receipt_shift_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='shift_name',
            field=models.CharField(blank=True, default=1, max_length=10, null=True),
        ),
    ]
