# Generated by Django 3.2.20 on 2024-02-29 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0010_auto_20240229_2355'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='branch_email',
            field=models.EmailField(blank=True, default=1, max_length=254, null=True),
        ),
    ]
