# Generated by Django 3.2.20 on 2024-02-29 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0011_branch_branch_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('email', models.EmailField(blank=True, default='', max_length=254, null=True)),
                ('password', models.CharField(blank=True, default='', max_length=30, null=True)),
                ('address', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('branch_email', models.EmailField(blank=True, default=1, max_length=254, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='branch',
            name='branch_email',
        ),
    ]
